# set information to info page /info
info:
  build:
    artifact: '@project.artifactId@'
    group: '@project.groupId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    finalName: '@project.build.finalName@'
    timestamp: '${spring.application.name}:${spring.application.instance_id:${random.value}}'


spring:
  logging:
    level:
      org.springframework: WARN

eureka:
  dashboard:
    path: dashboard
    enabled: true
#  instance:
#    leaseRenewalIntervalInSeconds: 3
#    metadataMap:
#      managementPath: /admin
#      instanceId: discoveryPrimary
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enableSelfPreservation: false
#    waitTimeInMsWhenSyncEmpty: 0
#    renewalPercentThreshold: 0.49
#  password: password
---
spring:
  profiles: local
server:
   port: 8761

eureka:
  datacenter: local
  environment: local
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8762/eureka/
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: peer1
server:
   port: 8761
eureka:
  environment: peer1
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
---
spring:
  profiles: peer2
server:
    port: 8762
eureka:
  environment: peer2
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/